# Generated by Django 5.1.2 on 2025-02-08 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_account_sub_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sub_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 19, 31, 35, 884131)),
        ),
    ]
