# Generated by Django 5.1.2 on 2025-02-08 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_account_sub_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='can_customize',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sub_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 20, 28, 52, 620826)),
        ),
    ]
