# Generated by Django 5.1.2 on 2025-02-09 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_subscription_can_customize_alter_account_sub_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sub_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 9, 9, 56, 38, 859347)),
        ),
    ]
