# Generated by Django 5.1.4 on 2025-02-25 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_account_sub_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sub_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 19, 9, 11, 885249)),
        ),
    ]
