# Generated by Django 5.1.2 on 2025-03-02 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_alter_account_sub_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sub_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 10, 4, 42, 473764)),
        ),
    ]
