# Generated by Django 5.1.2 on 2025-03-08 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_account_sub_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='can_customize',
        ),
        migrations.AddField(
            model_name='subscription',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sub_expire',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
