# Generated by Django 5.1.4 on 2025-01-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='path_qrcode',
            field=models.ImageField(default='1', upload_to='media/'),
        ),
    ]
