# Generated by Django 5.1.5 on 2025-02-01 19:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0003_qrcode_when_created'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='acc_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user_app.account'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='path_qrcode',
            field=models.ImageField(default='1', upload_to='images/qrcodes/'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 20, 53, 45, 40770)),
        ),
    ]
