# Generated by Django 5.1.5 on 2025-02-01 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0004_qrcode_acc_id_alter_qrcode_path_qrcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 21, 12, 20, 915660)),
        ),
    ]
