# Generated by Django 5.1.2 on 2025-02-08 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0005_alter_qrcode_when_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 19, 31, 35, 887123)),
        ),
    ]
