# Generated by Django 5.1.2 on 2025-02-08 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0006_alter_qrcode_when_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='color',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='color_back',
            field=models.CharField(default='ffffffff', max_length=8),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='color_front',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 20, 28, 52, 623929)),
        ),
    ]
