# Generated by Django 5.1.2 on 2025-02-09 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0007_remove_qrcode_color_qrcode_color_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 9, 9, 56, 38, 865332)),
        ),
    ]
