# Generated by Django 5.1.4 on 2025-02-15 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0008_alter_qrcode_link_alter_qrcode_when_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 19, 34, 45, 813685)),
        ),
    ]
