# Generated by Django 5.1.4 on 2025-02-25 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0011_alter_qrcode_when_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='when_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 19, 15, 41, 36438)),
        ),
    ]
